In [1]:
#q1
import requests

url = "https://community-open-weather-map.p.rapidapi.com/climate/month"
querystring = {"q":"Cairo"}
headers = {
    'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",
    'x-rapidapi-key': "2c3577747dmsh71a9a6384dfd79fp16c464jsn790e92b14490" #Kindly put your API-Key here :)
    }

response = requests.request("GET", url, headers=headers, params=querystring)
print(response.text)

{"cod":"200","city":{"id":360630,"name":"Cairo","coord":{"lon":31.2497,"lat":30.0626},"country":"EG"},"message":0.375173278,"list":[{"dt":1642118400,"humidity":59.9,"pressure":1017.75,"temp":{"average":287.12,"average_max":290.97,"average_min":283.11,"record_max":293.15,"record_min":277.8},"wind_speed":4.47},{"dt":1642204800,"humidity":63.27,"pressure":1019.25,"temp":{"average":286.89,"average_max":291.45,"average_min":282.65,"record_max":294.12,"record_min":276.99},"wind_speed":4.48},{"dt":1642291200,"humidity":57.76,"pressure":1017.88,"temp":{"average":286.19,"average_max":291.17,"average_min":281.83,"record_max":295,"record_min":276.32},"wind_speed":4.86},{"dt":1642377600,"humidity":60.96,"pressure":1017.27,"temp":{"average":286.6,"average_max":291.21,"average_min":281.4,"record_max":293.93,"record_min":275.03},"wind_speed":4.08},{"dt":1642464000,"humidity":59.32,"pressure":1018.62,"temp":{"average":286.67,"average_max":290.93,"average_min":281.7,"record_max":295.15,"record_min":274.36},"wind_speed":4.9},{"dt":1642550400,"humidity":63.17,"pressure":1019.84,"temp":{"average":286.26,"average_max":291.04,"average_min":281.27,"record_max":293.95,"record_min":274.57},"wind_speed":4.3},{"dt":1642636800,"humidity":58.39,"pressure":1021.31,"temp":{"average":286.25,"average_max":291.49,"average_min":281.48,"record_max":295,"record_min":275.24},"wind_speed":3.65},{"dt":1642723200,"humidity":54.07,"pressure":1020.47,"temp":{"average":287.23,"average_max":293.07,"average_min":281.59,"record_max":297.15,"record_min":276.61},"wind_speed":3.55},{"dt":1642809600,"humidity":53.7,"pressure":1018.68,"temp":{"average":287.9,"average_max":293.44,"average_min":282.56,"record_max":301.04,"record_min":276.06},"wind_speed":3.78},{"dt":1642896000,"humidity":55.81,"pressure":1017.87,"temp":{"average":287.7,"average_max":292.27,"average_min":282.73,"record_max":297.1,"record_min":277.64},"wind_speed":3.91},{"dt":1642982400,"humidity":56.6,"pressure":1017.74,"temp":{"average":288.09,"average_max":292.74,"average_min":283.38,"record_max":296.03,"record_min":277.36},"wind_speed":3.92},{"dt":1643068800,"humidity":57.74,"pressure":1018.05,"temp":{"average":287.92,"average_max":293,"average_min":282.2,"record_max":299.15,"record_min":275.7},"wind_speed":3.46},{"dt":1643155200,"humidity":54.63,"pressure":1017,"temp":{"average":287.86,"average_max":292.62,"average_min":282.61,"record_max":300.15,"record_min":273.39},"wind_speed":4.61},{"dt":1643241600,"humidity":56.83,"pressure":1016.67,"temp":{"average":287.38,"average_max":291.8,"average_min":282.34,"record_max":296,"record_min":278.65},"wind_speed":4.34},{"dt":1643328000,"humidity":55.14,"pressure":1018.82,"temp":{"average":286.77,"average_max":290.6,"average_min":282.86,"record_max":292.15,"record_min":277.33},"wind_speed":3.5},{"dt":1643414400,"humidity":56.1,"pressure":1020.11,"temp":{"average":286.63,"average_max":290.9,"average_min":282.2,"record_max":294.15,"record_min":276.37},"wind_speed":3.09},{"dt":1643500800,"humidity":54.62,"pressure":1020.15,"temp":{"average":286.64,"average_max":291.59,"average_min":281.83,"record_max":295.15,"record_min":276.68},"wind_speed":3.3},{"dt":1643587200,"humidity":54.55,"pressure":1019.76,"temp":{"average":286.93,"average_max":291.79,"average_min":282.1,"record_max":296.67,"record_min":276.41},"wind_speed":3.79},{"dt":1643673600,"humidity":58.68,"pressure":1019.31,"temp":{"average":287.57,"average_max":293.1,"average_min":282.31,"record_max":300.15,"record_min":277.07},"wind_speed":3.67},{"dt":1643760000,"humidity":61.32,"pressure":1018.99,"temp":{"average":287.91,"average_max":293.16,"average_min":282.9,"record_max":300.12,"record_min":276.49},"wind_speed":3.78},{"dt":1643846400,"humidity":59.98,"pressure":1019.63,"temp":{"average":287.58,"average_max":293.21,"average_min":282.47,"record_max":299.98,"record_min":276.6},"wind_speed":3.82},{"dt":1643932800,"humidity":58.14,"pressure":1018.92,"temp":{"average":287.99,"average_max":294.01,"average_min":282.33,"record_max":301.15,"record_min":275.28},"wind_speed":3.28},{"dt":1644019200,"humidity":52.56,"pressure":1017.27,"temp":{"average":289.2,"average_max":294.64,"average_min":283.65,"record_max":301.15,"record_min":276.27},"wind_speed":3.9},{"dt":1644105600,"humidity":52.18,"pressure":1016.77,"temp":{"average":288.8,"average_max":293.9,"average_min":284.02,"record_max":300.15,"record_min":274.88},"wind_speed":4.09},{"dt":1644192000,"humidity":53.86,"pressure":1016.88,"temp":{"average":288.49,"average_max":293.5,"average_min":283.57,"record_max":302.15,"record_min":275.86},"wind_speed":4.98},{"dt":1644278400,"humidity":51.01,"pressure":1018.13,"temp":{"average":289.05,"average_max":294.29,"average_min":284.37,"record_max":303.15,"record_min":278.01},"wind_speed":3.42},{"dt":1644364800,"humidity":55.81,"pressure":1018.38,"temp":{"average":288.47,"average_max":293.64,"average_min":283.49,"record_max":303.15,"record_min":276.65},"wind_speed":3.34},{"dt":1644451200,"humidity":57.12,"pressure":1017.87,"temp":{"average":287.92,"average_max":293.01,"average_min":283.19,"record_max":305.15,"record_min":276.94},"wind_speed":3.86},{"dt":1644537600,"humidity":56.96,"pressure":1018.09,"temp":{"average":287.4,"average_max":292.69,"average_min":282.43,"record_max":299.15,"record_min":271.79},"wind_speed":4.26},{"dt":1644624000,"humidity":57.5,"pressure":1018.04,"temp":{"average":287.74,"average_max":293.38,"average_min":282.96,"record_max":299.15,"record_min":278.07},"wind_speed":3.76}]}

In [5]:
import json
import pandas as pd
df_from_API = pd.DataFrame(json.loads(response.text)['list'])
df_from_API.head(20)

,dt,humidity,pressure,temp,wind_speed
0,1642118400,59.90,1017.75,"{'average': 287.12, 'average_max': 290.97, 'av...",4.47
1,1642204800,63.27,1019.25,"{'average': 286.89, 'average_max': 291.45, 'av...",4.48
2,1642291200,57.76,1017.88,"{'average': 286.19, 'average_max': 291.17, 'av...",4.86
3,1642377600,60.96,1017.27,"{'average': 286.6, 'average_max': 291.21, 'ave...",4.08
4,1642464000,59.32,1018.62,"{'average': 286.67, 'average_max': 290.93, 'av...",4.90
5,1642550400,63.17,1019.84,"{'average': 286.26, 'average_max': 291.04, 'av...",4.30
6,1642636800,58.39,1021.31,"{'average': 286.25, 'average_max': 291.49, 'av...",3.65
7,1642723200,54.07,1020.47,"{'average': 287.23, 'average_max': 293.07, 'av...",3.55
8,1642809600,53.70,1018.68,"{'average': 287.9, 'average_max': 293.44, 'ave...",3.78
9,1642896000,55.81,1017.87,"{'average': 287.7, 'average_max': 292.27, 'ave...",3.91
10,1642982400,56.60,1017.74,"{'average': 288.09, 'average_max': 292.74, 'av...",3.92
11,1643068800,57.74,1018.05,"{'average': 287.92, 'average_max': 293, 'avera...",3.46
12,1643155200,54.63,1017.00,"{'average': 287.86, 'average_max': 292.62, 'av...",4.61
13,1643241600,56.83,1016.67,"{'average': 287.38, 'average_max': 291.8, 'ave...",4.34
14,1643328000,55.14,1018.82,"{'average': 286.77, 'average_max': 290.6, 'ave...",3.50
15,1643414400,56.10,1020.11,"{'average': 286.63, 'average_max': 290.9, 'ave...",3.09
16,1643500800,54.62,1020.15,"{'average': 286.64, 'average_max': 291.59, 'av...",3.30
17,1643587200,54.55,1019.76,"{'average': 286.93, 'average_max': 291.79, 'av...",3.79
18,1643673600,58.68,1019.31,"{'average': 287.57, 'average_max': 293.1, 'ave...",3.67
19,1643760000,61.32,1018.99,"{'average': 287.91, 'average_max': 293.16, 'av...",3.78

In [6]:
print(df_from_API["temp"])

0     {'average': 287.12, 'average_max': 290.97, 'av...
1     {'average': 286.89, 'average_max': 291.45, 'av...
2     {'average': 286.19, 'average_max': 291.17, 'av...
3     {'average': 286.6, 'average_max': 291.21, 'ave...
4     {'average': 286.67, 'average_max': 290.93, 'av...
5     {'average': 286.26, 'average_max': 291.04, 'av...
6     {'average': 286.25, 'average_max': 291.49, 'av...
7     {'average': 287.23, 'average_max': 293.07, 'av...
8     {'average': 287.9, 'average_max': 293.44, 'ave...
9     {'average': 287.7, 'average_max': 292.27, 'ave...
10    {'average': 288.09, 'average_max': 292.74, 'av...
11    {'average': 287.92, 'average_max': 293, 'avera...
12    {'average': 287.86, 'average_max': 292.62, 'av...
13    {'average': 287.38, 'average_max': 291.8, 'ave...
14    {'average': 286.77, 'average_max': 290.6, 'ave...
15    {'average': 286.63, 'average_max': 290.9, 'ave...
16    {'average': 286.64, 'average_max': 291.59, 'av...
17    {'average': 286.93, 'average_max': 291.79, 'av...
18    {'average': 287.57, 'average_max': 293.1, 'ave...
19    {'average': 287.91, 'average_max': 293.16, 'av...
20    {'average': 287.58, 'average_max': 293.21, 'av...
21    {'average': 287.99, 'average_max': 294.01, 'av...
22    {'average': 289.2, 'average_max': 294.64, 'ave...
23    {'average': 288.8, 'average_max': 293.9, 'aver...
24    {'average': 288.49, 'average_max': 293.5, 'ave...
25    {'average': 289.05, 'average_max': 294.29, 'av...
26    {'average': 288.47, 'average_max': 293.64, 'av...
27    {'average': 287.92, 'average_max': 293.01, 'av...
28    {'average': 287.4, 'average_max': 292.69, 'ave...
29    {'average': 287.74, 'average_max': 293.38, 'av...
Name: temp, dtype: object

In [15]:
df = pd.concat([df_from_API, pd.json_normalize(df_from_API['temp'])], axis=1)

df.head(20)

,dt,humidity,pressure,temp,wind_speed,average,average_max,average_min,record_max,record_min
0,1642118400,59.90,1017.75,"{'average': 287.12, 'average_max': 290.97, 'av...",4.47,287.12,290.97,283.11,293.15,277.80
1,1642204800,63.27,1019.25,"{'average': 286.89, 'average_max': 291.45, 'av...",4.48,286.89,291.45,282.65,294.12,276.99
2,1642291200,57.76,1017.88,"{'average': 286.19, 'average_max': 291.17, 'av...",4.86,286.19,291.17,281.83,295.00,276.32
3,1642377600,60.96,1017.27,"{'average': 286.6, 'average_max': 291.21, 'ave...",4.08,286.60,291.21,281.40,293.93,275.03
4,1642464000,59.32,1018.62,"{'average': 286.67, 'average_max': 290.93, 'av...",4.90,286.67,290.93,281.70,295.15,274.36
5,1642550400,63.17,1019.84,"{'average': 286.26, 'average_max': 291.04, 'av...",4.30,286.26,291.04,281.27,293.95,274.57
6,1642636800,58.39,1021.31,"{'average': 286.25, 'average_max': 291.49, 'av...",3.65,286.25,291.49,281.48,295.00,275.24
7,1642723200,54.07,1020.47,"{'average': 287.23, 'average_max': 293.07, 'av...",3.55,287.23,293.07,281.59,297.15,276.61
8,1642809600,53.70,1018.68,"{'average': 287.9, 'average_max': 293.44, 'ave...",3.78,287.90,293.44,282.56,301.04,276.06
9,1642896000,55.81,1017.87,"{'average': 287.7, 'average_max': 292.27, 'ave...",3.91,287.70,292.27,282.73,297.10,277.64
10,1642982400,56.60,1017.74,"{'average': 288.09, 'average_max': 292.74, 'av...",3.92,288.09,292.74,283.38,296.03,277.36
11,1643068800,57.74,1018.05,"{'average': 287.92, 'average_max': 293, 'avera...",3.46,287.92,293.00,282.20,299.15,275.70
12,1643155200,54.63,1017.00,"{'average': 287.86, 'average_max': 292.62, 'av...",4.61,287.86,292.62,282.61,300.15,273.39
13,1643241600,56.83,1016.67,"{'average': 287.38, 'average_max': 291.8, 'ave...",4.34,287.38,291.80,282.34,296.00,278.65
14,1643328000,55.14,1018.82,"{'average': 286.77, 'average_max': 290.6, 'ave...",3.50,286.77,290.60,282.86,292.15,277.33
15,1643414400,56.10,1020.11,"{'average': 286.63, 'average_max': 290.9, 'ave...",3.09,286.63,290.90,282.20,294.15,276.37
16,1643500800,54.62,1020.15,"{'average': 286.64, 'average_max': 291.59, 'av...",3.30,286.64,291.59,281.83,295.15,276.68
17,1643587200,54.55,1019.76,"{'average': 286.93, 'average_max': 291.79, 'av...",3.79,286.93,291.79,282.10,296.67,276.41
18,1643673600,58.68,1019.31,"{'average': 287.57, 'average_max': 293.1, 'ave...",3.67,287.57,293.10,282.31,300.15,277.07
19,1643760000,61.32,1018.99,"{'average': 287.91, 'average_max': 293.16, 'av...",3.78,287.91,293.16,282.90,300.12,276.49

In [16]:
del df['temp']
df.head(20)

,dt,humidity,pressure,wind_speed,average,average_max,average_min,record_max,record_min
0,1642118400,59.90,1017.75,4.47,287.12,290.97,283.11,293.15,277.80
1,1642204800,63.27,1019.25,4.48,286.89,291.45,282.65,294.12,276.99
2,1642291200,57.76,1017.88,4.86,286.19,291.17,281.83,295.00,276.32
3,1642377600,60.96,1017.27,4.08,286.60,291.21,281.40,293.93,275.03
4,1642464000,59.32,1018.62,4.90,286.67,290.93,281.70,295.15,274.36
5,1642550400,63.17,1019.84,4.30,286.26,291.04,281.27,293.95,274.57
6,1642636800,58.39,1021.31,3.65,286.25,291.49,281.48,295.00,275.24
7,1642723200,54.07,1020.47,3.55,287.23,293.07,281.59,297.15,276.61
8,1642809600,53.70,1018.68,3.78,287.90,293.44,282.56,301.04,276.06
9,1642896000,55.81,1017.87,3.91,287.70,292.27,282.73,297.10,277.64
10,1642982400,56.60,1017.74,3.92,288.09,292.74,283.38,296.03,277.36
11,1643068800,57.74,1018.05,3.46,287.92,293.00,282.20,299.15,275.70
12,1643155200,54.63,1017.00,4.61,287.86,292.62,282.61,300.15,273.39
13,1643241600,56.83,1016.67,4.34,287.38,291.80,282.34,296.00,278.65
14,1643328000,55.14,1018.82,3.50,286.77,290.60,282.86,292.15,277.33
15,1643414400,56.10,1020.11,3.09,286.63,290.90,282.20,294.15,276.37
16,1643500800,54.62,1020.15,3.30,286.64,291.59,281.83,295.15,276.68
17,1643587200,54.55,1019.76,3.79,286.93,291.79,282.10,296.67,276.41
18,1643673600,58.68,1019.31,3.67,287.57,293.10,282.31,300.15,277.07
19,1643760000,61.32,1018.99,3.78,287.91,293.16,282.90,300.12,276.49

In [23]:
df = df.rename(columns={'record_min': 'temp_min','record_max': 'temp_max'})

In [24]:
df.head(20)

,dt,humidity,pressure,wind_speed,average,average_max,average_min,temp_max,temp_min
0,1642118400,59.90,1017.75,4.47,287.12,290.97,283.11,293.15,277.80
1,1642204800,63.27,1019.25,4.48,286.89,291.45,282.65,294.12,276.99
2,1642291200,57.76,1017.88,4.86,286.19,291.17,281.83,295.00,276.32
3,1642377600,60.96,1017.27,4.08,286.60,291.21,281.40,293.93,275.03
4,1642464000,59.32,1018.62,4.90,286.67,290.93,281.70,295.15,274.36
5,1642550400,63.17,1019.84,4.30,286.26,291.04,281.27,293.95,274.57
6,1642636800,58.39,1021.31,3.65,286.25,291.49,281.48,295.00,275.24
7,1642723200,54.07,1020.47,3.55,287.23,293.07,281.59,297.15,276.61
8,1642809600,53.70,1018.68,3.78,287.90,293.44,282.56,301.04,276.06
9,1642896000,55.81,1017.87,3.91,287.70,292.27,282.73,297.10,277.64
10,1642982400,56.60,1017.74,3.92,288.09,292.74,283.38,296.03,277.36
11,1643068800,57.74,1018.05,3.46,287.92,293.00,282.20,299.15,275.70
12,1643155200,54.63,1017.00,4.61,287.86,292.62,282.61,300.15,273.39
13,1643241600,56.83,1016.67,4.34,287.38,291.80,282.34,296.00,278.65
14,1643328000,55.14,1018.82,3.50,286.77,290.60,282.86,292.15,277.33
15,1643414400,56.10,1020.11,3.09,286.63,290.90,282.20,294.15,276.37
16,1643500800,54.62,1020.15,3.30,286.64,291.59,281.83,295.15,276.68
17,1643587200,54.55,1019.76,3.79,286.93,291.79,282.10,296.67,276.41
18,1643673600,58.68,1019.31,3.67,287.57,293.10,282.31,300.15,277.07
19,1643760000,61.32,1018.99,3.78,287.91,293.16,282.90,300.12,276.49

In [25]:
df.to_csv("panas_dataset_1from_api.csv", index=False)